# Generated by Django 5.2.15 on 2026-06-06 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("seo", "General SEO"),
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("facebook", "Facebook"),
                            ("twitter", "X / Twitter"),
                            ("tiktok", "TikTok"),
                            ("pinterest", "Pinterest"),
                            ("grammar", "Grammar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_text", models.TextField()),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "analysis histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
